// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLQpkSQzwg3DnbwKQUnAKXoaISwfJPU6c',
    appId: '1:958918793047:android:71a7532ba7fa9771021012',
    messagingSenderId: '958918793047',
    projectId: 'attendace-tracker-13587',
    storageBucket: 'attendace-tracker-13587.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCBVoxZM3COzFBt7bUhMIVboxKjcfla9U',
    appId: '1:958918793047:ios:0592e424b177d67e021012',
    messagingSenderId: '958918793047',
    projectId: 'attendace-tracker-13587',
    storageBucket: 'attendace-tracker-13587.appspot.com',
    iosBundleId: 'com.example.trackingAttendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCBVoxZM3COzFBt7bUhMIVboxKjcfla9U',
    appId: '1:958918793047:ios:0592e424b177d67e021012',
    messagingSenderId: '958918793047',
    projectId: 'attendace-tracker-13587',
    storageBucket: 'attendace-tracker-13587.appspot.com',
    iosBundleId: 'com.example.trackingAttendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCux5Ev37ba9bJJ7y35rB1Mz5I9BuKAPok',
    appId: '1:958918793047:web:758cdc89fe23c9e3021012',
    messagingSenderId: '958918793047',
    projectId: 'attendace-tracker-13587',
    authDomain: 'attendace-tracker-13587.firebaseapp.com',
    storageBucket: 'attendace-tracker-13587.appspot.com',
    measurementId: 'G-60YN36X4VP',
  );
}
